version: '3'
services:
  skillswapchat:
    image: skillswapchat:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=SkillSwap
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27011:27017"
    environment:
      - MONGO_INITDB_DATABASE=SkillSwap
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: